### ISSUE TITLE
Windows 7 x64 SP1 doesn't function correctly.

### ISSUE THREAD

**Issue by thomhughes** [tandasat/PgResarch#2] opened 2015-07-24 04:34 UTC
ntoskrnl!PoolBigPageTable could not be solved : 1168(0x00000490) : Element not found.

RegisterSymbolInformation failed. : 0(0x00000000) : The operation completed successfully.

-Windows 7 x64 SP1

ntoskrnl.exe hash 0x00552cf1

(I tried enabling test signing and kernel debugging)

**Comment by tandasat** [comment] 2015-07-24 04:54
Thanks for reporting the issue. With a quick test, I was not able to reproduce the issue with the same kernel version. Can you check if
1) the internet connection is available on the test VM, and
2) dbghelp.dll and symsrv.dll (those are in the release archive file, bin_DisPG.zip) are located at the same directory as DisPGLoader.exe?

It seems like DisPGLoader is not getting the symbol address.

**Comment by thomhughes** [comment] 2015-07-25 02:10
yeh I will try that now thanks

**Comment by thomhughes** [comment] 2015-07-25 02:13
Internet connectivity is available on the VM
dbghelp and symsrv.dll are in the same directory.

**Comment by tandasat** [comment] 2015-07-25 17:51
Cool. Close it. Feel free to reopen it if you think it is appropriate.

**Closed by tandasat** 2015-07-25 17:51 UTC
